Repository nhn-on7/marketgg-client, pull requests merged in 2022-08, with the labels that each got.

#105 인코딩 설정
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
Labels: Feat

#114 정적 리소스 권한 체크
  src/main/java/com/nhnacademy/marketgg/client/annotation/RoleCheck.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/RoleCheckAspect.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/Payload.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/Role.java
  src/main/java/com/nhnacademy/marketgg/client/oauth2/TokenRequest.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminPointController.java
  src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java
  src/main/java/com/nhnacademy/marketgg/client/web/RoleCheckTestController.java
  src/main/java/com/nhnacademy/marketgg/client/web/TestController.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalExceptionAdvice.java
  src/main/resources/static/css/bootstrap/bootstrap-grid.css.map
  src/main/resources/static/css/bootstrap/bootstrap.css.map
  src/main/resources/static/css/bootstrap/bootstrap.min.css.map
  src/test/java/com/nhnacademy/marketgg/client/ClientApplicationTests.java
Labels: Feat

#118 UI 공통 컴포넌트 및 템플릿 작성
  lombok.config
  src/main/resources/templates/fragments/common/footer.html
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/products/create-form.html
  src/main/resources/templates/fragments/products/table.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/admin/index.html
  src/main/resources/templates/pages/admin/products/form.html
  src/main/resources/templates/pages/admin/products/index.html
  src/main/resources/templates/pages/payments/index.html
Labels: Feat, Fix, Style

#120 Hotfix/multipart filter
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
Labels: Fix

#124 Cloud 연동 및 상품 UI 구현
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/SecurityApplicationInitializer.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/DefaultPageResult.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/ImageResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/RestResponsePage.java
  src/main/java/com/nhnacademy/marketgg/client/repository/ImageRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ImageAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/ImageService.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultImageService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ImageController.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/ProductController.java
  src/main/resources/static/plugins/marketgg/css/product-details.css
  src/main/resources/static/plugins/tui/toast.js
  src/main/resources/static/plugins/tui/viewer.js
  src/main/resources/templates/fragments/products/create-form.html
  src/main/resources/templates/fragments/products/details.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/form-layout.html
  src/main/resources/templates/products/index.html
  src/main/resources/templates/products/product-create-form.html
  src/main/resources/templates/products/product-details.html
  src/main/resources/templates/products/product-view.html
  src/main/resources/templates/products/retrieve-products.html
Labels: Feat, Style, Refactor

#128 상품 검색 관리
  src/main/java/com/nhnacademy/marketgg/client/dto/response/SearchProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminProductController.java
  src/test/java/com/nhnacademy/marketgg/client/service/ProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CsPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/ProductControllerTest.java
Labels: Feat, Docs, Test

#129 주문과 관련된 레이어 구성 및 기본적인 기능 추가
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/order/OrderAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/order/OrderRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/order/GgOrderService.java
  src/main/java/com/nhnacademy/marketgg/client/service/order/OrderService.java
  src/main/java/com/nhnacademy/marketgg/client/util/GgUrlUtils.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderController.java
  src/main/resources/static/css/orders/order-form.css
  src/main/resources/static/images/favicon.ico
  src/main/resources/templates/fragments/orders/radio-button.html
  src/main/resources/templates/pages/orders/order-details.html
  src/main/resources/templates/pages/orders/order-form.html
  src/main/resources/templates/pages/orders/order-list.html
Labels: Feat, Docs, Style, Chore

#131 Validation/Exception 업보청산
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CategoryCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CategoryUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CommentRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/LabelRegisterRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/PostRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/PostStatusUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/SearchRequest.java
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/CommentController.java
  src/main/java/com/nhnacademy/marketgg/client/web/CsPostController.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminCsPostController.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminLabelController.java
  src/main/java/com/nhnacademy/marketgg/client/web/member/MemberController.java
  src/main/resources/templates/board/faqs/create-form.html
  src/main/resources/templates/search/product-search-list.html
  src/test/java/com/nhnacademy/marketgg/client/service/MemberServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminCsPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CommentControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CsPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/MemberControllerTest.java
Labels: Feat, Fix, Refactor

#136 Feat: ThreadLocal 로 쿠키 확인, 메인 페이지 수정
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/RoleCheckAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/InterceptorConfigure.java
  src/main/java/com/nhnacademy/marketgg/client/config/RestTemplateInterceptorConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/SecurityApplicationInitializer.java
  src/main/java/com/nhnacademy/marketgg/client/context/SessionContext.java
  src/main/java/com/nhnacademy/marketgg/client/dto/MemberInfo.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/CookieInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/JwtRefreshInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/util/GgUrlUtils.java
  src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java
  src/main/java/com/nhnacademy/marketgg/client/web/IndexController.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberInfoController.java
  src/main/java/com/nhnacademy/marketgg/client/web/Oauth2Controller.java
  src/main/resources/templates/fragments/header.html
Labels: Feat

#151 로그인 수정
  .github/workflows/gradle.yml
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/LoginRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupRequest.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/ShaPasswordEncoder.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/resources/templates/pages/admin/products/form.html
  src/main/resources/templates/pages/admin/products/index.html
  src/main/resources/templates/pages/board/faqs/create-form.html
  src/main/resources/templates/pages/board/faqs/detail.html
  src/main/resources/templates/pages/board/faqs/index.html
  src/main/resources/templates/pages/board/faqs/update-form.html
  src/main/resources/templates/pages/board/notices/create-form.html
  src/main/resources/templates/pages/board/notices/detail.html
  src/main/resources/templates/pages/board/notices/index.html
  src/main/resources/templates/pages/board/notices/update-form.html
  src/main/resources/templates/pages/board/oto-inquiries/create-form.html
  src/main/resources/templates/pages/board/oto-inquiries/detail.html
  src/main/resources/templates/pages/board/oto-inquiries/index.html
  src/main/resources/templates/pages/dibs/index.html
  src/main/resources/templates/pages/ggpass/index.html
  src/main/resources/templates/pages/labels/index.html
  src/main/resources/templates/pages/orders/order-details.html
  src/main/resources/templates/pages/orders/order-form.html
  src/main/resources/templates/pages/orders/order-list.html
  src/main/resources/templates/pages/payments/index.html
  src/main/resources/templates/products/product-create-form.html
  src/main/resources/templates/products/product-view.html
Labels: Fix

#159 공통 응답 객체 수정
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/CommonResult.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/ResponseUtils.java
  src/main/java/com/nhnacademy/marketgg/client/repository/OauthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/GoogleAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/OauthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/cart/CartAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/cart/CartRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/GoogleAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductInquiryAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/Oauth2Service.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/GoogleLoginService.java
  src/main/java/com/nhnacademy/marketgg/client/web/Oauth2Controller.java
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/impl/GoogleLoginServiceTest.java
Labels: Refactor

#163 403 에러 해결
  src/main/java/com/nhnacademy/marketgg/client/annotation/Auth.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/RoleCheckAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/InterceptorConfigure.java
  src/main/java/com/nhnacademy/marketgg/client/config/RestTemplateConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/RestTemplateInterceptorConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/context/SessionContext.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/CommonResult.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/ResponseUtils.java
  src/main/java/com/nhnacademy/marketgg/client/filter/AuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/AuthenticationInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/CookieInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/JwtAddInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/JwtInfo.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/Payload.java
  src/main/java/com/nhnacademy/marketgg/client/repository/OauthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/GoogleAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/OauthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/cart/CartAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/cart/CartRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/GoogleAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductInquiryAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/Oauth2Service.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/GoogleLoginService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberInfoController.java
  src/main/java/com/nhnacademy/marketgg/client/web/Oauth2Controller.java
  src/main/java/com/nhnacademy/marketgg/client/web/ReviewController.java
  src/main/java/com/nhnacademy/marketgg/client/web/RoleCheckTestController.java
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/impl/GoogleLoginServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CartControllerTest.java
Labels: Fix, Refactor

#171 GG패스 삭제
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/member/MemberController.java
  src/main/resources/templates/pages/ggpass/index.html
  src/test/java/com/nhnacademy/marketgg/client/service/MemberServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/MemberControllerTest.java
Labels: Fix

#155 에러 페이지 핸들링
  src/main/java/com/nhnacademy/marketgg/client/web/error/ExceptionHandlingController.java
  src/main/resources/static/css/errors/404.css
  src/main/resources/templates/pages/errors/403.html
  src/main/resources/templates/pages/errors/404.html
  src/main/resources/templates/pages/errors/5xx.html
  src/main/resources/templates/pages/errors/default-error.html
Labels: Feat, Docs, Style

#174 레이아웃 정리
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderToPayment.java
  src/main/java/com/nhnacademy/marketgg/client/repository/order/OrderAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/payment/PaymentAdapter.java
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/admin-layout.html
  src/main/resources/templates/layouts/default-layout.html
  src/main/resources/templates/layouts/form-layout.html
  src/main/resources/templates/layouts/table-layout.html
  src/main/resources/templates/layouts/title-main-link-script.html
  src/main/resources/templates/layouts/title-main-link.html
  src/main/resources/templates/layouts/title-main-script.html
  src/main/resources/templates/layouts/title-main.html
  src/main/resources/templates/members/login.html
  src/main/resources/templates/pages/admin/products/form.html
  src/main/resources/templates/pages/admin/products/index.html
  src/main/resources/templates/pages/payments/index.html
  src/main/resources/templates/products/product-create-form.html
  src/main/resources/templates/products/product-view.html
  src/main/resources/templates/products/reviews/reviews.html
Labels: Fix, Style

#167 회원가입 로직 변경
  src/main/java/com/nhnacademy/marketgg/client/dto/request/SignupRequest.java
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberInfoController.java
Labels: Feat, Refactor

#184 공통 UI 보완
  src/main/java/com/nhnacademy/marketgg/client/config/LocaleConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/plugins/clickymenus/css/clicky-menus.css
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/templates/fragments/common/footer.html
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/gnb.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/title-main-link-script.html
  src/main/resources/templates/layouts/title-main-link.html
  src/main/resources/templates/layouts/title-main-script.html
  src/main/resources/templates/layouts/title-main.html
Labels: Feat, Docs, Style

#175 회원정보 수정, 삭제
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToAuth.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToShopMember.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberUpdateToAuth.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/SignupRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberSignupResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberUpdateToAuthResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberInfoController.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalControllerAdvice.java
  src/main/resources/templates/members/signup.html
Labels: Refactor

#188 장바구니
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/CartProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/filter/AuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/JwtAddInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/JwtInfo.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/Role.java
  src/main/java/com/nhnacademy/marketgg/client/util/GgUtils.java
  src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberInfoController.java
  src/main/java/com/nhnacademy/marketgg/client/web/cart/CartController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/css/carts/cart.css
  src/main/resources/static/css/members/login.css
  src/main/resources/static/js/carts/cart.js
  src/main/resources/static/js/products/product.js
  src/main/resources/templates/carts/index.html
  src/main/resources/templates/layouts/form-layout.html
  src/main/resources/templates/pages/carts/index.html
  src/main/resources/templates/pages/members/login.html
  src/main/resources/templates/pages/members/signup.html
  src/main/resources/templates/products/product-view.html
  src/test/java/com/nhnacademy/marketgg/client/web/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CartControllerTest.java
Labels: Feat, Refactor

#197 Feature/UI fix copark
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminLabelController.java
  src/main/java/com/nhnacademy/marketgg/client/web/member/DibController.java
  src/main/resources/application.yml
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/css/board/marketgg.board.css
  src/main/resources/static/css/dib/marketgg.dib.css
  src/main/resources/static/css/label/marketgg.label.css
  src/main/resources/templates/layouts/title-main-link.html
  src/main/resources/templates/mygg/dibs/index.html
  src/main/resources/templates/pages/admin/labels/index.html
  src/main/resources/templates/pages/board/faqs/create-form.html
  src/main/resources/templates/pages/board/faqs/index.html
  src/main/resources/templates/pages/board/faqs/update-form.html
  src/main/resources/templates/pages/board/notices/create-form.html
  src/main/resources/templates/pages/board/notices/index.html
  src/main/resources/templates/pages/board/notices/update-form.html
  src/main/resources/templates/pages/board/oto-inquiries/create-form.html
  src/main/resources/templates/pages/board/oto-inquiries/index.html
  src/main/resources/templates/pages/mygg/dibs/index.html
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/DibControllerTest.java
Labels: Feat, Fix, Chore

#214 Feat: 카트에서 주문으로 데이터 전송
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CartOrderRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/ProductToCartRequest.java
  src/main/java/com/nhnacademy/marketgg/client/web/cart/CartController.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderPageController.java
  src/main/resources/static/js/carts/cart.js
  src/main/resources/static/js/products/product.js
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/products/details.html
  src/main/resources/templates/pages/carts/index.html
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CartControllerTest.java
Labels: Feat

#218 관리자 UI 레이아웃 템플릿 추가 및 기타 버그 수정
  src/main/resources/static/plugins/autocomplete/css/autoComplete.02.css
  src/main/resources/static/plugins/autocomplete/js/index.js
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/static/plugins/myadmin/css/myadmin.css
  src/main/resources/static/plugins/tosspayments/js/payment.js
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/layouts/admin-title-main-link-script.html
  src/main/resources/templates/layouts/admin-title-main-link.html
  src/main/resources/templates/layouts/admin-title-main-script.html
  src/main/resources/templates/layouts/admin-title-main.html
  src/main/resources/templates/layouts/title-main-link-script.html
  src/main/resources/templates/layouts/title-main-link.html
  src/main/resources/templates/layouts/title-main-script.html
  src/main/resources/templates/layouts/title-main.html
  src/main/resources/templates/pages/admin/index.html
  src/main/resources/templates/pages/payments/details.html
  src/main/resources/templates/pages/payments/request-payment.html
  src/main/resources/templates/pages/payments/success-cancel-payment.html
  src/main/resources/templates/pages/payments/success-payment.html
Labels: Feat, Style

#221 관리자 카테고리 UI 1
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/css/category/category-index.css
  src/main/resources/static/plugins/myadmin/css/myadmin.css
  src/main/resources/static/plugins/myadmin/js/myadmin.js
  src/main/resources/templates/fragments/admin/sidebar.html
  src/main/resources/templates/layouts/admin-title-main-link-script.html
  src/main/resources/templates/pages/categories/index.html
Labels: Feat, Refactor

#225 상품검색 UI 구현
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/CommentResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/ProductListResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/PostAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/product/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/product/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/CsPostController.java
  src/main/java/com/nhnacademy/marketgg/client/web/IndexController.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminCsPostController.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminProductController.java
  src/main/java/com/nhnacademy/marketgg/client/web/product/ProductController.java
  src/main/resources/static/css/board/marketgg.board.css
  src/main/resources/static/plugins/autocomplete/js/index.js
  src/main/resources/static/plugins/autocomplete/js/search.js
  src/main/resources/templates/fragments/admin/sidebar.html
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/fragments/products/product-list.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/title-main-link-script.html
  src/main/resources/templates/layouts/title-main.html
  src/main/resources/templates/pages/board/faqs/index.html
  src/main/resources/templates/pages/board/notices/index.html
  src/main/resources/templates/pages/board/oto-inquiries/detail.html
  src/main/resources/templates/pages/board/oto-inquiries/index.html
  src/test/java/com/nhnacademy/marketgg/client/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/client/service/ProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminCsPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/ProductControllerTest.java
Labels: Fix, Docs

#227 후기 별점기능, 다국어처리, 삭제기능 구현
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/ReviewRatingResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/product/ReviewAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/product/ReviewRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/ReviewService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultReviewService.java
  src/main/java/com/nhnacademy/marketgg/client/web/product/ProductController.java
  src/main/java/com/nhnacademy/marketgg/client/web/product/ReviewController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/js/products/productDetails.js
  src/main/resources/static/js/products/review-editor.js
  src/main/resources/static/js/products/reviews.js
  src/main/resources/static/plugins/marketgg/css/product-details.css
  src/main/resources/templates/fragments/products/create-form.html
  src/main/resources/templates/fragments/products/details.html
  src/main/resources/templates/fragments/products/reviews/reviews.html
  src/main/resources/templates/layouts/admin-title-main-link-script.html
  src/main/resources/templates/pages/products/product-create-form.html
  src/main/resources/templates/pages/products/product-view.html
  src/test/java/com/nhnacademy/marketgg/client/web/ReviewControllerTest.java
Labels: Feat, Style, Refactor

#229 주문 프로세스 UI 테스트
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderFormResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderGivenCoupon.java
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderToPayment.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CartOrderRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/DeliveryAddressResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/order/OrderAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/order/OrderRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/order/GgOrderService.java
  src/main/java/com/nhnacademy/marketgg/client/service/order/OrderService.java
  src/main/java/com/nhnacademy/marketgg/client/web/cart/CartController.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderPageController.java
  src/main/java/com/nhnacademy/marketgg/client/web/payment/PaymentPageController.java
  src/main/resources/static/css/orders/order-form.css
  src/main/resources/static/plugins/autocomplete/css/autoComplete.02.css
  src/main/resources/static/plugins/clickymenus/css/clicky-menus.css
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/static/plugins/tosspayments/js/payment.js
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/pages/members/login.html
  src/main/resources/templates/pages/orders/order-form.html
  src/main/resources/templates/pages/payments/request-payment.html
Labels: Fix, Style

#223 Refactor/cart order
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/service/auth/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/client/web/cart/CartController.java
  src/main/resources/static/css/members/login.css
  src/main/resources/static/js/carts/cart.js
  src/main/resources/static/js/products/product.js
  src/main/resources/templates/fragments/products/details.html
  src/main/resources/templates/fragments/products/reviews/reviews.html
  src/main/resources/templates/pages/members/login.html
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthServiceTest.java
Labels: Fix, Refactor

#234 마이 페이지 UI 레이아웃 작성
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/web/IndexController.java
  src/main/resources/static/css/label/marketgg.label.css
  src/main/resources/static/css/mygg/marketgg.mygg.css
  src/main/resources/static/js/common/backToTop.js
  src/main/resources/static/js/common/viewport.js
  src/main/resources/static/plugins/autocomplete/js/index.js
  src/main/resources/static/plugins/clickymenus/css/clicky-menus.css
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/templates/fragments/common/footer.html
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/admin/labels/index.html
  src/main/resources/templates/pages/mygg/dibs/index.html
  src/main/resources/templates/pages/mygg/index.html
Labels: Feat, Style

#235 상품 UI Refactor 및 후기 버그 Fix
  src/main/java/com/nhnacademy/marketgg/client/dto/product/ProductUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/repository/product/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminProductController.java
  src/main/java/com/nhnacademy/marketgg/client/web/product/ReviewController.java
  src/main/resources/static/js/products/productDetails.js
  src/main/resources/static/plugins/marketgg/css/product-details.css
  src/main/resources/templates/fragments/admin/sidebar.html
  src/main/resources/templates/fragments/common/footer.html
  src/main/resources/templates/fragments/products/details.html
  src/main/resources/templates/fragments/products/product-list.html
  src/main/resources/templates/fragments/products/reviews/reviews.html
  src/main/resources/templates/fragments/products/table.html
  src/main/resources/templates/fragments/products/update-form.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/admin/products/form.html
  src/main/resources/templates/pages/admin/products/product-create-form.html
  src/main/resources/templates/pages/admin/products/product-modify-form.html
  src/main/resources/templates/pages/products/product-create-form.html
  src/main/resources/templates/pages/products/product-modify-form.html
  src/main/resources/templates/pages/products/retrieve-products.html
  src/test/java/com/nhnacademy/marketgg/client/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminProductControllerTest.java
Labels: Fix, Refactor

#230 회원 수정, 삭제 리팩터링 ui 작업
  src/main/java/com/nhnacademy/marketgg/client/dto/member/MemberUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/repository/member/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/member/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/member/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/member/MemberInfoController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/css/members/update.css
  src/main/resources/static/css/members/withdraw.css
  src/main/resources/static/js/delivery-addresses/delivery-address.js
  src/main/resources/static/js/members/update.js
  src/main/resources/static/js/members/withdraw.js
  src/main/resources/templates/pages/members/signup.html
  src/main/resources/templates/pages/mygg/delivery-addresses/form.html
  src/main/resources/templates/pages/mygg/delivery-addresses/index.html
  src/main/resources/templates/pages/mygg/members/update-form.html
  src/main/resources/templates/pages/mygg/members/withdraw-form.html
Labels: Feat, Refactor
