Repository nhn-on7/marketgg-client, pull requests merged in 2022-09, with the labels that each got.

#244 주문서 작성 폼 UI 개선
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/payment/PaymentResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/order/OrderAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/payment/PaymentAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/payment/PaymentRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/payment/PaymentService.java
  src/main/java/com/nhnacademy/marketgg/client/service/payment/TossPaymentService.java
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminCsPostController.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderPageController.java
  src/main/java/com/nhnacademy/marketgg/client/web/payment/PaymentController.java
  src/main/java/com/nhnacademy/marketgg/client/web/payment/PaymentPageController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/static/css/orders/order-form.css
  src/main/resources/static/css/payments/marketgg.payment.css
  src/main/resources/static/css/payments/marketgg.success.css
  src/main/resources/static/images/image-placeholder.png
  src/main/resources/static/js/orders/coupon.js
  src/main/resources/static/js/orders/order.js
  src/main/resources/static/plugins/autocomplete/js/index.js
  src/main/resources/static/plugins/clickymenus/css/clicky-menus.css
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/static/plugins/marketgg/css/product-details.css
  src/main/resources/static/plugins/tosspayments/js/payment.js
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/fragments/products/details.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/board/faqs/detail.html
  src/main/resources/templates/pages/board/notices/detail.html
  src/main/resources/templates/pages/board/oto-inquiries/detail.html
  src/main/resources/templates/pages/mygg/coupons/index.html
  src/main/resources/templates/pages/mygg/index.html
  src/main/resources/templates/pages/mygg/orders/order-form.html
  src/main/resources/templates/pages/orders/order-form.html
  src/main/resources/templates/pages/payments/cancel-payment.html
  src/main/resources/templates/pages/payments/index.html
  src/main/resources/templates/pages/payments/request-payment.html
  src/main/resources/templates/pages/payments/success-payment.html
Labels: Feat, Fix, Style

#242 Refactor: 탈퇴 회원 관리
  src/main/java/com/nhnacademy/marketgg/client/filter/AuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/auth/AuthService.java
  src/main/java/com/nhnacademy/marketgg/client/service/auth/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/client/util/LoginStatus.java
  src/main/java/com/nhnacademy/marketgg/client/web/auth/AuthController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/templates/pages/members/login.html
  src/test/java/com/nhnacademy/marketgg/client/web/AuthControllerTest.java
Labels: Feat

#248 Feature/log
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/filter/OriginFilter.java
  src/main/resources/log4j2-dev.xml
  src/main/resources/log4j2-local.xml
  src/main/resources/log4j2-prod.xml
Labels: Chore

#247 운송장 번호 에러처리 및 배송지 삭제 리팩토링
  src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminOrderController.java
  src/main/java/com/nhnacademy/marketgg/client/web/member/MemberInfoController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/pages/admin/orders/order-list.html
  src/main/resources/templates/pages/mygg/delivery-addresses/index.html
Labels: Feat, Refactor

#254 Refactor: 토큰 갱신 실패 시 Redis 에서 기존 토큰 삭제
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
Labels: Fix

#258 상품, 카테고리 캐싱 및 2depth 구현. + UI 오류수정
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/CacheConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/category/CategoryRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/category/CategoryAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/category/CategoryRepository.java
  src/main/java/com/nhnacademy/marketgg/client/service/category/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/client/service/category/DefaultCategoryService.java
  src/main/java/com/nhnacademy/marketgg/client/service/product/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/product/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/IndexController.java
  src/main/java/com/nhnacademy/marketgg/client/web/product/BaseController.java
  src/main/java/com/nhnacademy/marketgg/client/web/product/ProductController.java
  src/main/resources/ehcache-config.xml
  src/main/resources/static/css/marketgg.index.css
  src/main/resources/static/css/marketgg.menu.css
  src/main/resources/static/plugins/autocomplete/css/autoComplete.02.css
  src/main/resources/static/plugins/clickymenus/css/clicky-menus.css
  src/main/resources/static/plugins/clickymenus/js/clickyMenus.js
  src/main/resources/static/plugins/marketgg/css/marketgg.common.css
  src/main/resources/templates/fragments/admin/sidebar.html
  src/main/resources/templates/fragments/common/gnb.html
  src/main/resources/templates/fragments/products/create-form.html
  src/main/resources/templates/fragments/products/update-form.html
  src/main/resources/templates/layouts/form-layout.html
  src/main/resources/templates/layouts/title-main-link-script.html
  src/main/resources/templates/layouts/title-main-link.html
  src/main/resources/templates/layouts/title-main-script.html
  src/main/resources/templates/layouts/title-main.html
  src/main/resources/templates/pages/products/product-view.html
  src/test/java/com/nhnacademy/marketgg/client/web/ProductControllerTest.java
Labels: Feat, Refactor

#259 Style: 장바구니 Input 태그 스타일 변경
  src/main/resources/templates/pages/carts/index.html
Labels: Style

#261 Hotfix: Logout 수정
  src/main/java/com/nhnacademy/marketgg/client/web/auth/AuthController.java
  src/main/resources/log4j2-prod.xml
  src/main/resources/templates/index.html
Labels: Fix

#262 Hotfix: AOP 경로 변경
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
Labels: Fix

#263 주문 Refactoring
  src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderDetailRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/payment/PaymentConfirmRequest.java
  src/main/java/com/nhnacademy/marketgg/client/service/order/GgOrderService.java
  src/main/java/com/nhnacademy/marketgg/client/web/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/client/web/payment/PaymentController.java
  src/main/resources/message_en.properties
  src/main/resources/message_ko.properties
  src/main/resources/templates/pages/admin/orders/order-details.html
  src/main/resources/templates/pages/admin/orders/order-list.html
  src/main/resources/templates/pages/mygg/orders/order-details.html
  src/main/resources/templates/pages/orders/order-form.html
Labels: Refactor

#264 Refactor: Error Controller Advice 에러페이지 경로 추가
  src/main/java/com/nhnacademy/marketgg/client/config/CacheConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalControllerAdvice.java
Labels: Refactor
