Repository nhn-on7/marketgg-client, pull requests merged in 2022-07, with the labels that each got.

#12 Feat: 라벨 등록 구현/테스트코드 작성 #1
  src/main/java/com/nhnacademy/marketgg/client/dto/LabelRegisterRequest.java
  src/main/java/com/nhnacademy/marketgg/client/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/main/resources/templates/labels/create-form.html
  src/main/resources/templates/labels/index.html
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
Labels: Feat, Test

#15 라벨 조회 pr
  src/main/java/com/nhnacademy/marketgg/client/dto/LabelRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/client/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/main/resources/templates/labels/retrieve.html
  src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
Labels: Feat, Test

#16 라벨 삭제 pr
  src/main/java/com/nhnacademy/marketgg/client/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
Labels: Feat, Style, Test

#19 Feat: 상품 등록 기능 구현 #8
  src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/service/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/resources/products/index.html
Labels: Feat

#20 Feat: 상품 전체 조회 기능 구현 #11
  src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/service/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
Labels: Feat

#17 라벨 등록/조회/삭제 pr
  src/main/java/com/nhnacademy/marketgg/client/dto/LabelRegisterRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/LabelRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/client/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/main/resources/templates/labels/create-form.html
  src/main/resources/templates/labels/index.html
  src/main/resources/templates/labels/retrieve.html
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
Labels: Feat, Fix, Style, Test

#23 Feature/products create 이미지 등록
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfiguration.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/product-form.html
  src/main/resources/templates/product-view.html
Labels: Feat

#24 상품 스쿼드 중간 병합
  productRequest.http
  src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/resources/templates/products/index.html
  src/main/resources/templates/products/product-details.html
  src/main/resources/templates/products/retrieve-products.html
Labels: Feat

#25 Feat: 상품 단건 조회 기능 구현 #22
  src/main/resources/templates/products/product-details.html
  src/main/resources/templates/products/retrieve-products.html
Labels: Feat

#29 Feature/category create
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CategoryCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultCategoryService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminCategoryController.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/main/resources/templates/categories/create-form.html
  src/main/resources/templates/categories/index.html
  src/main/resources/templates/categories/update-form.html
  src/test/java/com/nhnacademy/marketgg/client/web/AdminCategoryControllerTest.java
Labels: Feat, Test

#38 Refactor: Spring @Configuration annotation 수정 #37
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/resources/application.yml
Labels: Feat, Refactor

#44 Feat: 상품 삭제 기능 구현
  src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
Labels: Feat

#46 Feature/category UI
  src/main/resources/templates/categories/create-form.html
  src/main/resources/templates/categories/index.html
  src/main/resources/templates/categories/update-form.html
Labels: Feat

#48 AOP 설정 완료
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/ClientApplication.java
  src/main/java/com/nhnacademy/marketgg/client/config/LogAspect.java
Labels: Feat

#49 Fix: Toast API 관련 코드 수정
  src/main/resources/static/js/toast.js
  src/main/resources/templates/products/product-form.html
Labels: Fix

#52 에디터 추가에 따른 상품 수정기능 수정
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/resources/application.yml
  src/main/resources/templates/products/index.html
  src/main/resources/templates/products/product-details.html
  src/main/resources/templates/products/product-modify-form.html
  src/main/resources/templates/products/retrieve-products.html
Labels: Fix

#54 GG 패스 클라이언트 구현 완료
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/dto/Message.java
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/CategoryAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/LabelAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminCategoryController.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberController.java
  src/main/resources/application.yml
  src/main/resources/templates/ggpass/index.html
  src/main/resources/templates/message.html
  src/test/java/com/nhnacademy/marketgg/client/web/AdminCategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/MemberControllerTest.java
Labels: Feat, Fix, Style, Test

#57 Docs: 자바 독 작성 완료
  src/main/java/com/nhnacademy/marketgg/client/config/LogAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/repository/CategoryRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/LabelRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/CategoryAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/LabelAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/client/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminCategoryController.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
  src/main/resources/templates/categories/create-form.html
  src/main/resources/templates/labels/index.html
  src/test/java/com/nhnacademy/marketgg/client/web/AdminCategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
Labels: Docs

#43 Feat: Security 기본 설정 #42
  .github/PULL_REQUEST_TEMPLATE
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/resources/templates/users/login.html
Labels: Feat

#61 Docs: 상품 레포지토리, DTO 자바독 작성 #59
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductModifyRequest.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/ProductRepository.java
Labels: Docs

#62 Feature/products review
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductModifyRequest.java
  src/main/java/com/nhnacademy/marketgg/client/domain/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/products/index.html
  src/main/resources/templates/products/product-details.html
  src/main/resources/templates/products/product-form.html
  src/main/resources/templates/products/product-modify-form.html
  src/main/resources/templates/products/product-view.html
  src/main/resources/templates/products/retrieve-products.html
Labels: Fix, Refactor

#65 Feature/products convention
  src/main/java/com/nhnacademy/marketgg/client/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
Labels: Style

#67 상품 클라이언트 머지 요청합니다.
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/ProductModifyRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/products/index.html
  src/main/resources/templates/products/product-details.html
  src/main/resources/templates/products/product-form.html
  src/main/resources/templates/products/product-modify-form.html
  src/main/resources/templates/products/product-view.html
  src/main/resources/templates/products/retrieve-products.html
Labels: Fix

#75 Style: typo 수정 및 디렉터리 변경 (closed #71)
  src/main/resources/static/js/clikcymenus/clickyMenus.js
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/includes/header.html
Labels: Style

#72 클라이언트 서버 로그인 기능 구현
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/LogAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/InterceptorConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/LoginRequest.java
  src/main/java/com/nhnacademy/marketgg/client/exception/LoginFailException.java
  src/main/java/com/nhnacademy/marketgg/client/exception/SecureManagerException.java
  src/main/java/com/nhnacademy/marketgg/client/exception/ServerException.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/JwtRefreshInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/JwtInfo.java
  src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java
  src/main/resources/application.yml
  src/main/resources/templates/users/login.html
Labels: Feat

#78 Feature/point
  src/main/java/com/nhnacademy/marketgg/client/dto/response/PointRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/PointRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/PointAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/PointService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultPointService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AdminPointController.java
  src/main/java/com/nhnacademy/marketgg/client/web/PointController.java
  src/main/resources/templates/points/admin-retrieve-members.html
  src/main/resources/templates/points/index.html
  src/test/java/com/nhnacademy/marketgg/client/ClientApplicationTests.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminPointControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/PointControllerTest.java
Labels: Feat, Test

#81 Feature/service test
  src/test/java/com/nhnacademy/marketgg/client/service/CategoryServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/DibServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/LabelServiceTest.java
Labels: Test

#77 로그아웃
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/InterceptorConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/client/exception/LoginFailException.java
  src/main/java/com/nhnacademy/marketgg/client/exception/LogoutException.java
  src/main/java/com/nhnacademy/marketgg/client/interceptor/JwtRefreshInterceptor.java
  src/main/java/com/nhnacademy/marketgg/client/jwt/JwtInfo.java
  src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java
  src/main/resources/application.yml
Labels: Feat

#83 AOP 를 이용하여 회원 정보 요청
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/annotation/Member.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/AspectUtils.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/dto/MemberInfo.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/AuthResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/CommonResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/ListResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/common/SingleResponse.java
  src/main/java/com/nhnacademy/marketgg/client/exception/ClientException.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/web/TestController.java
Labels: Feat

#88 Feat: 회원가입, 회원정보 수정, 회원탈퇴
  src/main/java/com/nhnacademy/marketgg/client/dto/request/EmailRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToAuth.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToShopMember.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberUpdateToAuth.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/EmailExistResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/EmailUseResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberSignupResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberUpdateToAuthResponse.java
  src/main/java/com/nhnacademy/marketgg/client/exception/ServerException.java
  src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberAjaxController.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberController.java
  src/main/resources/templates/member/signup.html
  src/test/java/com/nhnacademy/marketgg/client/controller/MemberControllerTest.java
Labels: Feat, Docs

#89 Refactor: 회원탈퇴 로직 수정
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToShopMember.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberWithdrawRequest.java
  src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
Labels: Refactor

#91 상품 검색 서비스 구현 PR
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/Alert.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/SearchRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchProduct.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchProductForCategory.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchProductForPrice.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchToCategoryForPrice.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/Sort.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SortForPrice.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/sortdata/Id.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/sortdata/Price.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/sortdata/Score.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/Bool.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/BoolQuery.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/MultiMatch.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/Must.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/Query.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/response/SearchProductResponse.java
  src/main/java/com/nhnacademy/marketgg/client/repository/SearchProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/SearchProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/SearchProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultSearchProductService.java
  src/main/java/com/nhnacademy/marketgg/client/utils/KoreanToEnglishTranslator.java
  src/main/java/com/nhnacademy/marketgg/client/utils/subutils/ConvertToEnglishUtil.java
  src/main/java/com/nhnacademy/marketgg/client/web/SearchProductController.java
  src/main/resources/application.yml
  src/main/resources/clientCertificate.p12
  src/main/resources/templates/search/search-list.html
  src/test/java/com/nhnacademy/marketgg/client/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/SearchProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/SearchProductControllerTest.java
Labels: Feat, Fix, Docs, Style, Test

#92 Fix: 테스트코드 오류 해결
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/web/MemberAjaxController.java
  src/test/java/com/nhnacademy/marketgg/client/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/MemberControllerTest.java
Labels: Fix

#90 Hotfix: Compile Error 해결
  build.gradle
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java
  src/main/resources/application.yml
Labels: Fix

#94 [ES] Adapter Refactoring
  src/main/java/com/nhnacademy/marketgg/client/config/ElasticConfig.java
  src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/SearchRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchProduct.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchProductForCategory.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchProductForPrice.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SearchToCategoryForPrice.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/Sort.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/SortForPrice.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/sortdata/Id.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/sortdata/Price.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/product/sortdata/Score.java
  src/main/java/com/nhnacademy/marketgg/client/repository/SearchProductRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/SearchProductAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/SearchProductService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultSearchProductService.java
  src/main/java/com/nhnacademy/marketgg/client/web/SearchProductController.java
  src/test/java/com/nhnacademy/marketgg/client/service/SearchProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/SearchProductControllerTest.java
Labels: Feat, Fix, Refactor

#97 Controller 클래스에 MemberInfo 전달
  src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
  src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java
  src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalExceptionAdvice.java
Labels: Feat

#100 Feat: 예외 처리 템플릿 생성 #99
  src/main/java/com/nhnacademy/marketgg/client/exception/ClientException.java
  src/main/java/com/nhnacademy/marketgg/client/exception/NotFoundException.java
  src/main/java/com/nhnacademy/marketgg/client/exception/ServerException.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalControllerAdvice.java
Labels: Feat

#106 공지사항/1:1문의/FAQ 클라이언트
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/SearchRequestBodyForBool.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/Bool.java
  src/main/java/com/nhnacademy/marketgg/client/dto/elastic/request/searchutil/Must.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/CommentRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/request/PostRequest.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/CommentResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/PostResponse.java
  src/main/java/com/nhnacademy/marketgg/client/dto/response/PostResponseForOtoInquiry.java
  src/main/java/com/nhnacademy/marketgg/client/repository/CommentRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/PostRepository.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/CommentAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/PostAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/repository/impl/SearchAdapter.java
  src/main/java/com/nhnacademy/marketgg/client/service/CommentService.java
  src/main/java/com/nhnacademy/marketgg/client/service/PostService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultCommentService.java
  src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultPostService.java
  src/main/java/com/nhnacademy/marketgg/client/web/CommentController.java
  src/main/java/com/nhnacademy/marketgg/client/web/PostController.java
  src/main/java/com/nhnacademy/marketgg/client/web/SearchBoardController.java
  src/main/java/com/nhnacademy/marketgg/client/web/SearchProductController.java
  src/main/resources/templates/board/faqs/create-form.html
  src/main/resources/templates/board/faqs/detail.html
  src/main/resources/templates/board/faqs/index.html
  src/main/resources/templates/board/faqs/update-form.html
  src/main/resources/templates/board/notices/create-form.html
  src/main/resources/templates/board/notices/detail.html
  src/main/resources/templates/board/notices/index.html
  src/main/resources/templates/board/notices/update-form.html
  src/main/resources/templates/board/oto-inquiries/create-form.html
  src/main/resources/templates/board/oto-inquiries/detail.html
  src/main/resources/templates/board/oto-inquiries/index.html
  src/main/resources/templates/board/oto-inquiries/update-form.html
  src/main/resources/templates/search/board-search-list.html
  src/test/java/com/nhnacademy/marketgg/client/service/CategoryServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/CommentServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/service/PostServiceTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/AdminPointControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/CommentControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/PostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/SearchBoardControllerTest.java
  src/test/java/com/nhnacademy/marketgg/client/web/SearchProductControllerTest.java
Labels: Feat, Docs, Style, Test
